name: Jago
favicon: null
layout_spectrum: 0.9942866968922317
typography_spectrum: 0.5515674978960305
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9230198308359832
  lightness: 0.48745554545894265
  saturation: 0.28533533378504217
  rhythmicContrast: 0.8631403092294931
purpose: []
